name: LogicMonitor Collector
description: |
  The collector is an application that runs on a server within your infrastructure and uses standard monitoring protocols to intelligently monitor devices within your infrastructure.
version: 0.1
category: Monitoring
maintainer: "Jeff Wozniak <jeff.wozniak@logicmonitor.com>"
license: The MIT License
projectURL: https://github.com/logicmonitor/docker_lm_collector
