name: LogicMonitor
description: SaaS-based performance monitoring for modern IT infrastructure
version: latest
category: Monitoring
maintainer: "Logic Monitor <techops@logicmonitor.com>"
license: The MIT License
projectURL: https://github.com/logicmonitor/docker_lm_collector
